name: bldui
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  uilib:
    path: ../../uilib
  dartlib:
    path: ../../dartlib

  cupertino_icons: ^1.0.8
  json_editor_flutter: ^1.4.2
  flutter_bloc: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

